#include <string>

#include "EglFuncID.h"

std::string egl_id_name_map[FUNID_EGL_END - 1] = {
    "eglMakeCurrent",
    "eglSwapBuffers_sync",
    "eglWaitGL",
    "eglWaitNative",
    "eglWaitClient",
    "eglClientWaitSync",
    "eglGetSyncAttrib",
    "eglChooseConfig",
    "eglCreatePbufferSurface",
    "eglCreateWindowSurface",
    "eglCreateContext",
    "eglDestroyContext",
    "eglDestroySurface",
    "eglTerminate",
    "eglIamComposer",
    "eglGetDisplay",
    "eglBindTexImage",
    "eglReleaseTexImage",
    "eglSurfaceAttrib",
    "eglSwapInterval",
    "eglReleaseThread",
    "eglCreateSync",
    "eglDestroySync",
    "eglCreateImage",
    "eglDestroyImage",
    "eglWaitSync",
    "eglGetNativeClientBufferANDROID",
    "eglSwapBuffers",
    "eglQueueBuffer",
    "eglTP",
    "eglTerminateThread",
    "eglSetGraphicBufferID",
    "eglGetGBufferType",
    "eglFenceWaitSync",
    "eglFenceSetSync",
    "eglGBufferDestroy",
};